version: '3'
services:
  web:
    image: nginx:1.13.11-alpine
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - "./www:/usr/share/nginx/html"
  php:
    build:
      context: dockerfile
      dockerfile: php-fpm.docker
    links:
      - db
    volumes:
      - "./www:/usr/share/nginx/html"
  db:
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: "--locale=ja_JP.UTF8"
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"